package Interfaces.MenuAdmin;

import Clases.Administrador;
import Clases.Calendario;
import Clases.Empleado;
import Clases.Paneles;
import Clases.Tabla;
import Clases.TextPrompt;
import Clases.Vendedor;
import Lista.ListaEmpleado;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alessansro Rios
 */
public class pnGestionEmpleados extends javax.swing.JPanel implements Paneles {

    DefaultTableModel mTablaEmpleados;
    Empleado empleado;
    Tabla tabla = new Tabla();
    Calendario tiempo = new Calendario();
    ListaEmpleado listaEmpleado = new ListaEmpleado();

    public pnGestionEmpleados() {
        initComponents();

        mTablaEmpleados = (DefaultTableModel) tbEmpleados.getModel();
        placeHolder();
        mostrarTiempo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frm_RegistrarEmpleado = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtApellidosEmpleado = new javax.swing.JTextField();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtTelefonoEmpleado = new javax.swing.JTextField();
        txtUserEmpleado = new javax.swing.JTextField();
        txtDniEmpleado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jboxTipoEmpleado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtPassEmpleado = new javax.swing.JPasswordField();
        head = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        pnEmpleados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleados = new javax.swing.JTable();
        btnNuevoEmpleado = new javax.swing.JButton();
        btnBorrarEmpleado = new javax.swing.JButton();

        frm_RegistrarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        frm_RegistrarEmpleado.setMinimumSize(new java.awt.Dimension(590, 390));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("TIPO DE EMPLEADO");

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtApellidosEmpleado.setBorder(null);

        txtNombreEmpleado.setBorder(null);

        txtTelefonoEmpleado.setBorder(null);

        txtUserEmpleado.setBorder(null);

        txtDniEmpleado.setBorder(null);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jboxTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Administrador", "Vendedor" }));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRAR NUEVO EMPLEADO");

        javax.swing.GroupLayout frm_RegistrarEmpleadoLayout = new javax.swing.GroupLayout(frm_RegistrarEmpleado.getContentPane());
        frm_RegistrarEmpleado.getContentPane().setLayout(frm_RegistrarEmpleadoLayout);
        frm_RegistrarEmpleadoLayout.setHorizontalGroup(
            frm_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_RegistrarEmpleadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(frm_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(txtTelefonoEmpleado)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(txtDniEmpleado)
                    .addComponent(txtApellidosEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(frm_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jboxTipoEmpleado, 0, 220, Short.MAX_VALUE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(txtUserEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(txtPassEmpleado))
                .addGap(35, 35, 35))
            .addGroup(frm_RegistrarEmpleadoLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        frm_RegistrarEmpleadoLayout.setVerticalGroup(
            frm_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_RegistrarEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(frm_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frm_RegistrarEmpleadoLayout.createSequentialGroup()
                        .addGroup(frm_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frm_RegistrarEmpleadoLayout.createSequentialGroup()
                                .addComponent(txtUserEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPassEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frm_RegistrarEmpleadoLayout.createSequentialGroup()
                                .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtApellidosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(frm_RegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frm_RegistrarEmpleadoLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jboxTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(frm_RegistrarEmpleadoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(txtDniEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(frm_RegistrarEmpleadoLayout.createSequentialGroup()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setBackground(new java.awt.Color(211, 10, 20));
        head.setMaximumSize(new java.awt.Dimension(700, 150));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LISTA DE EMPLEADOS ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hora");

        labelHora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelHora.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha");

        labelFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout headLayout = new javax.swing.GroupLayout(head);
        head.setLayout(headLayout);
        headLayout.setHorizontalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(469, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headLayout.setVerticalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 150));

        pnEmpleados.setMaximumSize(new java.awt.Dimension(700, 450));
        pnEmpleados.setName(""); // NOI18N

        tbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Nombres", "Apellidos", "DNI", "Telefono", "Usuario", "Contraseña", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tbEmpleados);

        btnNuevoEmpleado.setBackground(new java.awt.Color(211, 10, 20));
        btnNuevoEmpleado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNuevoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnNuevoEmpleado.setText("NUEVO");
        btnNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEmpleadoActionPerformed(evt);
            }
        });

        btnBorrarEmpleado.setBackground(new java.awt.Color(211, 10, 20));
        btnBorrarEmpleado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBorrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarEmpleado.setText("BORRAR");
        btnBorrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnEmpleadosLayout = new javax.swing.GroupLayout(pnEmpleados);
        pnEmpleados.setLayout(pnEmpleadosLayout);
        pnEmpleadosLayout.setHorizontalGroup(
            pnEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(pnEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevoEmpleado)
                .addGap(49, 49, 49)
                .addComponent(btnBorrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnEmpleadosLayout.setVerticalGroup(
            pnEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(btnBorrarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(pnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 700, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEmpleadoActionPerformed
        // TODO add your handling code here:
        frm_RegistrarEmpleado.setVisible(true);
        frm_RegistrarEmpleado.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnNuevoEmpleadoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String tipoEmpleado = jboxTipoEmpleado.getSelectedItem().toString();

        if (!verificaCampos().equals("")) {
            JOptionPane.showMessageDialog(null, "Verifique los Dastos en el campo: " + verificaCampos());
        } else {
            switch (tipoEmpleado) {
                case "Administrador" -> {
                    empleado = new Administrador();
                    empleado.setNombre(txtNombreEmpleado.getText());
                    empleado.setApellido(txtApellidosEmpleado.getText());
                    empleado.setDni(txtDniEmpleado.getText());
                    empleado.setTelefono(txtTelefonoEmpleado.getText());
                    empleado.setNombreUsuario(txtUserEmpleado.getText());
                    empleado.setPassword(txtPassEmpleado.getText());
                    empleado.setTipoEmpleado(jboxTipoEmpleado.getSelectedItem().toString());

                    listaEmpleado.agregarEmpleado(empleado);
                    agregar();
                    limpiaCampos();
                    break;
                }
                case "Vendedor" -> {
                    empleado = new Vendedor();

                    empleado.setNombre(txtNombreEmpleado.getText());
                    empleado.setApellido(txtApellidosEmpleado.getText());
                    empleado.setDni(txtDniEmpleado.getText());
                    empleado.setTelefono(txtTelefonoEmpleado.getText());
                    empleado.setNombreUsuario(txtUserEmpleado.getText());
                    empleado.setPassword(txtPassEmpleado.getText());
                    empleado.setTipoEmpleado(jboxTipoEmpleado.getSelectedItem().toString());
                    
                    listaEmpleado.agregarEmpleado(empleado);
                    agregar();
                    limpiaCampos();
                    break;
                }
                default -> {
                    JOptionPane.showMessageDialog(null, "Hubo un error");
                    break;
                }
            }

        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBorrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarEmpleadoActionPerformed
        // TODO add your handling code here:
        tabla.borrarDatosTabla(mTablaEmpleados, tbEmpleados);
    }//GEN-LAST:event_btnBorrarEmpleadoActionPerformed

    @Override
    public void placeHolder() {
        TextPrompt nombre = new TextPrompt("Nombre", txtNombreEmpleado);
        TextPrompt Apellido = new TextPrompt("Apellido", txtApellidosEmpleado);
        TextPrompt dni = new TextPrompt("DNI", txtDniEmpleado);
        TextPrompt telefono = new TextPrompt("Telefono Personal", txtTelefonoEmpleado);
        TextPrompt usuario = new TextPrompt("Usuario", txtUserEmpleado);
        TextPrompt contraseña = new TextPrompt("Contraseña", txtPassEmpleado);
    }

    @Override
    //agregamos un Empleado
    public void agregar() {
        String nombre = empleado.getNombre();
        String apellido = empleado.getApellido();
        String dni = empleado.getDni();
        String telefono = empleado.getTelefono();
        String nombreUsuario = empleado.getNombreUsuario();
        String password = empleado.getPassword();
        String tipo = empleado.getTipoEmpleado();
        //agregamos a la tabla
        mTablaEmpleados.addRow(new Object[]{
            mTablaEmpleados.getRowCount() + 1, nombre, apellido, dni, telefono, nombreUsuario, password, tipo
        });
    }

    private String verificaCampos() {
        if (txtNombreEmpleado.getText().equals("")) {
            return "Nombres";
        }
        if (txtApellidosEmpleado.getText().equals("")) {
            return "Apellidos";
        }
        if (txtDniEmpleado.getText().equals("")) {
            return "DNI";
        }
        if (txtTelefonoEmpleado.getText().equals("")) {
            return "Telefono";
        }
        if (txtUserEmpleado.getText().equals("")) {
            return "Usuario";
        }
        if (txtPassEmpleado.getText().equals("")) {
            return "Contraseña";
        }
        if (jboxTipoEmpleado.getSelectedIndex() == 0) {
            return "Tipo Empleado";
        }
        return "";
    }

    public void mostrarTiempo() {
        labelFecha.setText(tiempo.fechaCompleta);
        labelHora.setText(tiempo.horaCompleta);
    }

    void limpiaCampos() {
        txtApellidosEmpleado.setText("");
        txtDniEmpleado.setText("");
        txtNombreEmpleado.setText("");
        txtPassEmpleado.setText("");
        txtTelefonoEmpleado.setText("");
        txtUserEmpleado.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarEmpleado;
    private javax.swing.JButton btnNuevoEmpleado;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JFrame frm_RegistrarEmpleado;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JComboBox<String> jboxTipoEmpleado;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JPanel pnEmpleados;
    private javax.swing.JTable tbEmpleados;
    private javax.swing.JTextField txtApellidosEmpleado;
    private javax.swing.JTextField txtDniEmpleado;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JPasswordField txtPassEmpleado;
    private javax.swing.JTextField txtTelefonoEmpleado;
    private javax.swing.JTextField txtUserEmpleado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarPanel(JPanel p) {
    }
}
