package Interfaces.MenuAdmin;

import Clases.Calendario;
import Clases.Empleado;
import Clases.Paneles;
import Clases.Producto;
import Clases.Tabla;
import Clases.TextPrompt;
import Lista.ListaProducto;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alessansro Rios
 */
public class pnGestionProductos extends javax.swing.JPanel implements Paneles {

    DefaultTableModel mTablaProducto;
    Tabla tabla= new Tabla();
    Producto producto = new Producto();
    ListaProducto listaProducto= new ListaProducto();
    Calendario tiempo = new Calendario();

    public pnGestionProductos() {
        initComponents();
        mTablaProducto = (DefaultTableModel) tbProductos.getModel();
        placeHolder();
        mostrarTiempo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frm_RegistrarProductos = new javax.swing.JFrame();
        txtNombreProducto = new javax.swing.JTextField();
        txtIdProducto = new javax.swing.JTextField();
        txtPrecioUni = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtMarca = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jboxCategoriaProducto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        head = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        pnProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        btnNuevoProducto = new javax.swing.JButton();
        btnBorrarProducto = new javax.swing.JButton();

        frm_RegistrarProductos.setMinimumSize(new java.awt.Dimension(590, 390));

        txtNombreProducto.setBorder(null);

        txtIdProducto.setBorder(null);

        txtPrecioUni.setBorder(null);

        txtMarca.setBorder(null);

        txtCantidad.setBorder(null);
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Categoria");

        jboxCategoriaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Granos", "Carnes", "Frutas", "Limpieza", "Bebidas", "Frios", "Bebidas Alcholicas" }));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRAR NUEVO PRODUCTO");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setText("S/");

        javax.swing.GroupLayout frm_RegistrarProductosLayout = new javax.swing.GroupLayout(frm_RegistrarProductos.getContentPane());
        frm_RegistrarProductos.getContentPane().setLayout(frm_RegistrarProductosLayout);
        frm_RegistrarProductosLayout.setHorizontalGroup(
            frm_RegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_RegistrarProductosLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(150, 150, 150))
            .addGroup(frm_RegistrarProductosLayout.createSequentialGroup()
                .addGroup(frm_RegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frm_RegistrarProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(frm_RegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(txtIdProducto)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_RegistrarProductosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecioUni, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(frm_RegistrarProductosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)))
                .addGap(27, 27, 27)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(frm_RegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMarca)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jboxCategoriaProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        frm_RegistrarProductosLayout.setVerticalGroup(
            frm_RegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_RegistrarProductosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(frm_RegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frm_RegistrarProductosLayout.createSequentialGroup()
                        .addGroup(frm_RegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(frm_RegistrarProductosLayout.createSequentialGroup()
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombreProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frm_RegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioUni, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frm_RegistrarProductosLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jboxCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setBackground(new java.awt.Color(211, 10, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LISTA DE PRODUCTOS ");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora");

        labelHora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelHora.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha");

        labelFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout headLayout = new javax.swing.GroupLayout(head);
        head.setLayout(headLayout);
        headLayout.setHorizontalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addContainerGap(468, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headLayout.setVerticalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 150));

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Nombre", "Precio Unidad", "Categoria", "Marca", "Cantidad", "ID"
            }
        ));
        jScrollPane1.setViewportView(tbProductos);

        btnNuevoProducto.setBackground(new java.awt.Color(211, 10, 20));
        btnNuevoProducto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        btnNuevoProducto.setText("NUEVO");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        btnBorrarProducto.setBackground(new java.awt.Color(211, 10, 20));
        btnBorrarProducto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBorrarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarProducto.setText("BORRAR");
        btnBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnProductosLayout = new javax.swing.GroupLayout(pnProductos);
        pnProductos.setLayout(pnProductosLayout);
        pnProductosLayout.setHorizontalGroup(
            pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(pnProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevoProducto)
                .addGap(18, 18, 18)
                .addComponent(btnBorrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnProductosLayout.setVerticalGroup(
            pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(btnBorrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(pnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 700, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        // TODO add your handling code here:
        frm_RegistrarProductos.setVisible(true);
        frm_RegistrarProductos.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:

        if (verificaCampos().equals("")) {
            producto.setNombre(txtNombreProducto.getText());
            producto.setIdProducto(txtIdProducto.getText());
            producto.setCantidad(Integer.parseInt(txtCantidad.getText()));
            producto.setPrecioUnitario(Double.parseDouble(txtPrecioUni.getText()));
            producto.setMarca(txtMarca.getText());
            producto.setCategoria(jboxCategoriaProducto.getSelectedItem().toString());
            //agregamos el producto
            
            agregar();//metodo interface paneles, para este caso es agregar productos.
            listaProducto.agregarProducto(producto);
            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(null, "Verifique los datos en: " + verificaCampos());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarProductoActionPerformed
        // TODO add your handling code here:
        tabla.borrarDatosTabla(mTablaProducto, tbProductos);
    }//GEN-LAST:event_btnBorrarProductoActionPerformed

    @Override
    //agregar producto
    public void agregar() {
        String nombre = producto.getNombre();
        String id = producto.getIdProducto();
        double precioUni = producto.getPrecioUnitario();
        int cantidad = producto.getCantidad();
        String marca = producto.getMarca();
        String categoria = producto.getCategoria();

        mTablaProducto.addRow(new Object[]{
            mTablaProducto.getRowCount() + 1, nombre, precioUni, categoria, marca, cantidad, id
        });
    }

    void limpiarCampos() {
        txtCantidad.setText("");
        txtIdProducto.setText("");
        txtMarca.setText("");
        txtNombreProducto.setText("");
        txtPrecioUni.setText("");
        jboxCategoriaProducto.setSelectedIndex(0);
    }

    private String verificaCampos() {
        if (txtCantidad.getText().equals("")) {
            return "Cantidad";
        }
        if (txtIdProducto.getText().equals("")) {
            return "ID producto";
        }
        if (txtMarca.getText().equals("")) {
            return "Marca";
        }
        if (txtNombreProducto.getText().equals("")) {
            return "Nombre Producto";
        }
        if (txtPrecioUni.getText().equals("")) {
            return "Precio Unitario";
        }
        if (jboxCategoriaProducto.getSelectedIndex() == 0) {
            return "Categoria del Producto";
        }
        return "";
    }

    public void mostrarTiempo() {
        labelFecha.setText(tiempo.fechaCompleta);
        labelHora.setText(tiempo.horaCompleta);
    }

    @Override
    public void placeHolder() {
        TextPrompt nombre, marca, id, cantidad, precio;

        nombre = new TextPrompt("Nombre del Producto", txtNombreProducto);
        id = new TextPrompt("ID producto", txtIdProducto);
        marca = new TextPrompt("Marca", txtMarca);
        cantidad = new TextPrompt("Cantidad de Unidades", txtCantidad);
        precio = new TextPrompt("Precio Unitario", txtPrecioUni);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarProducto;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JFrame frm_RegistrarProductos;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JComboBox<String> jboxCategoriaProducto;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JPanel pnProductos;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioUni;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarPanel(JPanel p) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
