package Interfaces;

import Interfaces.MenuVendedor.Jfrm_MenuVendedor;
import Clases.TextPrompt;
import Interfaces.MenuAdmin.Jfrm_MenuAdministrador;
import Clases.Administrador;
import Clases.Empleado;
import Clases.Vendedor;
import Lista.ListaEmpleado;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Alessandro Rios
 */
public class Jfrm_Login extends javax.swing.JFrame {

    //declaracion de variable polimorfica
    Empleado empleado;
    String op ;
    ListaEmpleado listaEmpleados= new ListaEmpleado();

    public Jfrm_Login() {
        initComponents();
        this.setTitle("LOGIN");
        this.setLocationRelativeTo(null);
        placeHolders();
    }

    @Override//Agregamos una img al logo del sistema
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/logo-erickson.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuario = new javax.swing.ButtonGroup();
        pnLogin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        rbtnVendedor = new javax.swing.JRadioButton();
        rbtnAdmin = new javax.swing.JRadioButton();
        pnImg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoEmpresa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLogin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user1.png"))); // NOI18N

        btnIngresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel2.setText("LOGIN");

        Usuario.add(rbtnVendedor);
        rbtnVendedor.setText("Vendedor");
        rbtnVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnVendedorMouseClicked(evt);
            }
        });
        rbtnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVendedorActionPerformed(evt);
            }
        });

        Usuario.add(rbtnAdmin);
        rbtnAdmin.setText("Administrador");
        rbtnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnLoginLayout = new javax.swing.GroupLayout(pnLogin);
        pnLogin.setLayout(pnLoginLayout);
        pnLoginLayout.setHorizontalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(108, 108, 108))
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLoginLayout.createSequentialGroup()
                        .addComponent(rbtnVendedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnAdmin)
                        .addGap(40, 40, 40))
                    .addGroup(pnLoginLayout.createSequentialGroup()
                        .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnLoginLayout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabel4)
                                    .addGap(23, 23, 23))
                                .addGroup(pnLoginLayout.createSequentialGroup()
                                    .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsuario)
                                        .addGroup(pnLoginLayout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(157, Short.MAX_VALUE))))
        );
        pnLoginLayout.setVerticalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(21, 21, 21)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnVendedor)
                    .addComponent(rbtnAdmin))
                .addGap(26, 26, 26)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(pnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 300, 400));

        pnImg.setBackground(new java.awt.Color(211, 10, 20));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE VENTAS");

        logoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-erickson.png"))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("©Alessandro Rios");

        javax.swing.GroupLayout pnImgLayout = new javax.swing.GroupLayout(pnImg);
        pnImg.setLayout(pnImgLayout);
        pnImgLayout.setHorizontalGroup(
            pnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnImgLayout.createSequentialGroup()
                .addGroup(pnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnImgLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(logoEmpresa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnImgLayout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
            .addGroup(pnImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnImgLayout.setVerticalGroup(
            pnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnImgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoEmpresa)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        getContentPane().add(pnImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:

        String campos = verificaCampos();
        //empleado: objeto clase empleado
        if (campos.equals("")) {
            switch (op) {
                case "Administrador" -> {
                    //empleado: objeto clase administrador
                    empleado = new Administrador();
                    
                    empleado.setNombreUsuario("admin");
                    empleado.setPassword("admin");
                    
                    listaEmpleados.agregarEmpleado(empleado);
                    
                    boolean login = listaEmpleados.login(txtUsuario.getText(), txtPassword.getText());

                    //instanciamos el frame que queremos que muestre
                    Jfrm_MenuAdministrador menuAdmin = new Jfrm_MenuAdministrador();
                    verificacionLogin(login, menuAdmin, this);// metodo que verifica el login y trae al frm
                    break;
                }
                case "Vendedor" -> {
                    //empleado: objeto clase vendedor
                    empleado = new Vendedor();
                    empleado.setNombreUsuario("vendedor");
                    empleado.setPassword("vendedor");
                    listaEmpleados.agregarEmpleado(empleado);
                    
                    boolean login = listaEmpleados.login(txtUsuario.getText(), txtPassword.getText());

                    //instanciamos el frame que queremos que muestree
                    Jfrm_MenuVendedor menuVendedor = new Jfrm_MenuVendedor();

                    verificacionLogin(login, menuVendedor, this);// metofo que verifica el login y trae el frm
                    break;
                }
                default -> {
                    JOptionPane.showMessageDialog(null, "Hubo un error. intentelo nuevamente");
                    break;
                }
            }
        } else JOptionPane.showMessageDialog(null, "Hubo un incoveniente con el campo: "+campos);

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void rbtnVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnVendedorMouseClicked
        // TODO add your handling code here:
        empleado = new Empleado();
        empleado.setTipoEmpleado(rbtnVendedor.getText());
        op = empleado.getTipoEmpleado();
    }//GEN-LAST:event_rbtnVendedorMouseClicked

    private void rbtnAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnAdminMouseClicked
        // TODO add your handling code here:
        empleado = new Empleado();
        empleado.setTipoEmpleado(rbtnAdmin.getText());
        op = empleado.getTipoEmpleado();
    }//GEN-LAST:event_rbtnAdminMouseClicked

    private void rbtnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnVendedorActionPerformed

    void placeHolders() {
        TextPrompt usuario, contraseña;
        usuario = new TextPrompt("Usuario", txtUsuario);
        contraseña = new TextPrompt("Contraseña", txtPassword);
    }

    void verificacionLogin(boolean ingreso, javax.swing.JFrame ventana, javax.swing.JFrame log) {
        if (ingreso == true) {
            ventana.setVisible(true);
            log.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Credenciales incorrectas, intentelo nuevamente");
        }
    }

    String verificaCampos() {
        if (txtUsuario.getText().equals("")) 
            return "Usuario";
        
        if (txtPassword.getText().equals(""))
            return "Contraseña";
        
        if (rbtnAdmin.isSelected()== false && rbtnVendedor.isSelected()== false) 
            return "Seleccione un tipo de empleado";
        return "";
    }
    
    void resetearCampos(){
       txtPassword.setText("");
       txtUsuario.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfrm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup Usuario;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel logoEmpresa;
    private javax.swing.JPanel pnImg;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JRadioButton rbtnAdmin;
    private javax.swing.JRadioButton rbtnVendedor;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
