package Interfaces.MenuVendedor;

import Clases.Calendario;
import Clases.Cliente;
import Clases.Pago;
import Clases.Producto;
import Lista.ListaClientes;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alessandro Rios
 */
public class pnVentas extends javax.swing.JPanel {

    Producto producto = new Producto();
    Pago pago = new Pago();
    ListaClientes listaCliente = new ListaClientes();
    Calendario tiempo = new Calendario();
    DefaultTableModel mTablaItems, mTablaItemsBoleta;

    public pnVentas() {
        initComponents();

        mTablaItems = (DefaultTableModel) tbItems.getModel();
        mTablaItemsBoleta = (DefaultTableModel) tbItemBoleta.getModel();

        mostrarTiempo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frm_boleta = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        logoEmpresa1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbItemBoleta = new javax.swing.JTable();
        labelNombreCliente = new javax.swing.JLabel();
        labelDatoComprobante1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jboxTipoComprobante = new javax.swing.JComboBox<>();
        labelDatoComprobante = new javax.swing.JLabel();
        txtDatoComprobante = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItems = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtIgv = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtPago = new javax.swing.JTextField();
        txtVuelto = new javax.swing.JTextField();
        txtCantidadItems = new javax.swing.JTextField();
        btnRegistrarVenta = new javax.swing.JButton();
        btnCalcularVuelto = new javax.swing.JButton();
        pnAgregarProducto = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jboxProducto = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        frm_boleta.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(211, 10, 20));

        logoEmpresa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-erickson.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(logoEmpresa1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoEmpresa1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel11.setText("Datos Cliente:");

        jLabel12.setText("Detalle Venta");

        jLabel13.setText("Importe Total:");

        jLabel14.setText("Pago con:");

        jLabel15.setText("Vuelto:");

        jLabel16.setText("Fecha:");

        jLabel17.setText("Hora:");

        jLabel18.setText("Nombre:");

        jLabel19.setText("DNI o RUC:");

        tbItemBoleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Producto", "Cantidad", "Importe"
            }
        ));
        jScrollPane2.setViewportView(tbItemBoleta);

        javax.swing.GroupLayout frm_boletaLayout = new javax.swing.GroupLayout(frm_boleta.getContentPane());
        frm_boleta.getContentPane().setLayout(frm_boletaLayout);
        frm_boletaLayout.setHorizontalGroup(
            frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(frm_boletaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frm_boletaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(frm_boletaLayout.createSequentialGroup()
                        .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDatoComprobante1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_boletaLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
            .addGroup(frm_boletaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
            .addGroup(frm_boletaLayout.createSequentialGroup()
                .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frm_boletaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_boletaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)))
                .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addGap(0, 289, Short.MAX_VALUE))
        );
        frm_boletaLayout.setVerticalGroup(
            frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_boletaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frm_boletaLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frm_boletaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDatoComprobante1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(23, 23, 23)
                        .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel12)))
                    .addComponent(labelFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frm_boletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frm_boletaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 630));
        setMinimumSize(new java.awt.Dimension(700, 630));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de Facturacion"));

        jLabel2.setText("Comprobante:");

        jboxTipoComprobante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Factura", "Boleta" }));
        jboxTipoComprobante.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jboxTipoComprobanteItemStateChanged(evt);
            }
        });

        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jboxTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(labelDatoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDatoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDatoComprobante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jboxTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDatoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCliente)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Productos"));

        tbItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Eliminar", "Producto", "Marca", "Cantidad", "P. Unitario", "Importe"
            }
        ));
        tbItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbItems);

        jLabel3.setText("Cantidad de Productos:");

        jLabel6.setText("Subtotal: ");

        jLabel7.setText("IGV 18% :");

        jLabel8.setText("Total:");

        jLabel9.setText("Paga con:");

        jLabel10.setText("Vuelto:");

        btnRegistrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recibo.png"))); // NOI18N
        btnRegistrarVenta.setText("REGISTRAR VENTA");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        btnCalcularVuelto.setText("Calcular Vuelto");
        btnCalcularVuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularVueltoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(txtIgv)
                    .addComponent(txtTotal))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtVuelto))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnCalcularVuelto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadItems, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidadItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnCalcularVuelto))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtIgv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pnAgregarProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Productos"));

        jLabel4.setText("Producto:");

        jLabel5.setText("Cantidad");

        jboxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Chocolate", "Gaseosa", "Helado", "Carne de Res", "Arroz" }));
        jboxProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jboxProductoItemStateChanged(evt);
            }
        });

        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        jLabel1.setText("Precio ");

        jLabel23.setText("S/");

        javax.swing.GroupLayout pnAgregarProductoLayout = new javax.swing.GroupLayout(pnAgregarProducto);
        pnAgregarProducto.setLayout(pnAgregarProductoLayout);
        pnAgregarProductoLayout.setHorizontalGroup(
            pnAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAgregarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGroup(pnAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAgregarProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jboxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnAgregarProductoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnAgregarProductoLayout.setVerticalGroup(
            pnAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAgregarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jboxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jboxTipoComprobanteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jboxTipoComprobanteItemStateChanged
        // TODO add your handling code here:
        TipoComprobante();
    }//GEN-LAST:event_jboxTipoComprobanteItemStateChanged

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:

        /*
        En caso de que el cliente exista en la lista de clientes, mostrar sus datos en un panel.
        En caso contrario ,mostraar un panel donde pueda agregar al cliente en la lista de clientes
        */
        if (jboxTipoComprobante.getSelectedIndex() == 1) {
            String ruc = txtDatoComprobante.getText();

            Cliente cliente = listaCliente.buscarClienteRuc(ruc);

            if (cliente != null) {
                
            } else {
                JOptionPane.showMessageDialog(null, "Cliente no disponible");
                
            }

        }

        if (jboxTipoComprobante.getSelectedIndex() == 2) {
            String dni = txtDatoComprobante.getText();
            Cliente cliente = listaCliente.buscarClienteDni(dni);

            if (cliente != null) {
                JOptionPane.showInputDialog(cliente.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Cliente no disponible");

            }
        }

    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void tbItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItemsMouseClicked
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el producto?");

        if (op == 0) {
            mTablaItems.removeRow(tbItems.getSelectedRow());
        }
        calcularMontos();
        cantidadProductos();
    }//GEN-LAST:event_tbItemsMouseClicked

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
        agregarProducto(jboxProducto.getSelectedIndex(), jboxProducto.getSelectedItem().toString());
        cantidadProductos();
        calcularMontos();
        limpiarCampos();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void jboxProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jboxProductoItemStateChanged
        // TODO add your handling code here:
        switch (jboxProducto.getSelectedIndex()) {
            case 1 -> {
                txtPrecioProducto.setText("5");
            }
            case 2 -> {
                txtPrecioProducto.setText("2");
            }
            case 3 -> {
                txtPrecioProducto.setText("3");
            }
            case 4 -> {
                txtPrecioProducto.setText("15");
            }
            case 5 -> {
                txtPrecioProducto.setText("4");
            }
        }
    }//GEN-LAST:event_jboxProductoItemStateChanged

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        // TODO add your handling code here:
        if (verificaCampos().equals("")) {
            frm_boleta.setVisible(true);
            frm_boleta.setSize(466, 610);
            frm_boleta.setLocationRelativeTo(null);

        } else
            JOptionPane.showMessageDialog(null, verificaCampos());
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnCalcularVueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularVueltoActionPerformed
        // TODO add your handling code here:
        pagar();
    }//GEN-LAST:event_btnCalcularVueltoActionPerformed

    void agregarProducto(int op, String nombre) {
        String accion = "Eliminar";
        double precio;
        int cantidad;

        switch (op) {
            case 1 -> {
                precio = 5;
                cantidad = Integer.parseInt(txtCantidad.getText());
                mTablaItems.addRow(new Object[]{
                    accion, nombre, "Sublime", cantidad, precio, calcularImporte(cantidad, precio)
                });
                //tabla boleta
                itemBoleta(nombre, cantidad, precio);
            }
            case 2 -> {
                precio = 2;
                cantidad = Integer.parseInt(txtCantidad.getText());
                mTablaItems.addRow(new Object[]{
                    accion, nombre, "Inka Kola", cantidad, precio, calcularImporte(cantidad, precio)
                });
                //tabla boleta
                itemBoleta(nombre, cantidad, precio);
            }
            case 3 -> {
                precio = 3;
                cantidad = Integer.parseInt(txtCantidad.getText());
                mTablaItems.addRow(new Object[]{
                    accion, nombre, "Donofrio", cantidad, precio, calcularImporte(cantidad, precio)
                });
                //tabla boleta
                itemBoleta(nombre, cantidad, precio);
            }
            case 4 -> {
                precio = 15;
                cantidad = Integer.parseInt(txtCantidad.getText());
                mTablaItems.addRow(new Object[]{
                    accion, nombre, "Grills", cantidad, precio, calcularImporte(cantidad, precio)
                });
                //tabla boleta
                itemBoleta(nombre, cantidad, precio);
            }
            case 5 -> {
                precio = 4;
                cantidad = Integer.parseInt(txtCantidad.getText());
                mTablaItems.addRow(new Object[]{
                    accion, nombre, "Grano de Oro", cantidad, precio, calcularImporte(cantidad, precio)
                });
                //tabla boleta
                itemBoleta(nombre, cantidad, precio);
            }
        }
    }

    void TipoComprobante() {
        int op = jboxTipoComprobante.getSelectedIndex();

        switch (op) {
            case 0 -> {
                labelDatoComprobante.setText("");
                break;
            }
            case 1 -> {
                labelDatoComprobante.setText("RUC");
                break;
            }
            case 2 -> {
                labelDatoComprobante.setText("DNI");
                break;
            }
        }
    }

    double calcularImporte(int cantidad, double precio) {
        return cantidad * precio;
    }

    void total() {
        double total;
        total = Double.parseDouble(txtSubtotal.getText()) + Double.parseDouble(txtIgv.getText());
        txtTotal.setText(String.valueOf(total));
    }

    void igv() {

        double subTotal = Double.parseDouble(txtSubtotal.getText());
        double igv = subTotal * 0.18;
        BigDecimal numero = new BigDecimal(igv);
        BigDecimal redondeo = numero.setScale(2, RoundingMode.CEILING);
        txtIgv.setText(redondeo.toString());
    }

    void SubTotal() {
        double total = 0;
        for (int i = 0; i < tbItems.getRowCount(); i++) {
            total += Float.parseFloat(tbItems.getValueAt(i, 5).toString());
        }
        txtSubtotal.setText(String.valueOf(total));
    }

    void cantidadProductos() {

        int cantidadItems = mTablaItems.getRowCount();
        txtCantidadItems.setText(String.valueOf(cantidadItems));
    }

    void calcularMontos() {
        SubTotal();
        igv();
        total();
    }

    void limpiarCampos() {
        jboxProducto.setSelectedIndex(0);
        txtCantidad.setText("");
        txtPrecioProducto.setText("");
    }

    void pagar() {

        pago.setPago(Double.parseDouble(txtPago.getText()));
        pago.setPrecioTotal(Double.parseDouble(txtTotal.getText()));
        double vuelto = pago.calcularVuelto();

        BigDecimal numero = new BigDecimal(vuelto);

        BigDecimal redondeo = numero.setScale(2, RoundingMode.CEILING);

        txtVuelto.setText(redondeo.toString());
    }

    void mostrarTiempo() {
        labelFecha.setText(tiempo.fechaCompleta);
        labelHora.setText(tiempo.horaCompleta);
    }

    void itemBoleta(String nombre, int cantidad, double precio) {
        mTablaItemsBoleta.addRow(new Object[]{
            mTablaItemsBoleta.getRowCount(), nombre, cantidad, calcularImporte(cantidad, precio)
        });
    }

    String verificaCampos() {
        if (jboxTipoComprobante.getSelectedIndex() == 0 && txtDatoComprobante.getText().equals("")) {
            return "Seleccione un tipo de comprobante o ingrese datos de comprobante";
        }
        if (txtCantidad.getText().equals("") && jboxProducto.getSelectedIndex() == 0) {
            return "Seleccione un producto o ingrese una cantidad";
        }
        if (txtPago.getText().equals("")) {
            return "Ingrese el pago de los productos";
        }
        return "";
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCalcularVuelto;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JFrame frm_boleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jboxProducto;
    private javax.swing.JComboBox<String> jboxTipoComprobante;
    private javax.swing.JLabel labelDatoComprobante;
    private javax.swing.JLabel labelDatoComprobante1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelNombreCliente;
    private javax.swing.JLabel logoEmpresa1;
    private javax.swing.JPanel pnAgregarProducto;
    private javax.swing.JTable tbItemBoleta;
    private javax.swing.JTable tbItems;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadItems;
    private javax.swing.JTextField txtDatoComprobante;
    private javax.swing.JTextField txtIgv;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVuelto;
    // End of variables declaration//GEN-END:variables

}
